repos:
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.16.1
  hooks:
    - id: stylua # or stylua-system / stylua-github
      args: [--indent-type, Spaces, --column-width, "100"]
      exclude: ^.*plugin/ 


