vim.pack.add {
    "https://github.com/folke/snacks.nvim",
}

require("snacks").setup { picker = { enabled = true } }
local nmap = function(keys, func, desc)
    vim.keymap.set("n", keys, func, { noremap = true, silent = true, desc = desc })
end
local nxmap = function(keys, func, desc)
    vim.keymap.set({ "n", "x" }, keys, func, { noremap = true, silent = true, desc = desc })
end

nmap("<leader>sf", function()
    Snacks.picker.smart()
end, "Files")
nmap("<leader>sh", function()
    Snacks.picker.help()
end, "Help pages")
nmap("<leader>sg", function()
    Snacks.picker.grep()
end, "Grep")
nmap("<leader>sG", function()
    Snacks.picker.grep_buffers()
end, "Grep open buffers")
nxmap("<leader>sw", function()
    Snacks.picker.grep_word()
end, "Visual selection or word")
nmap("<leader>sd", function()
    Snacks.picker.diagnostics()
end, "Diagnostics")
nmap("<leader>sD", function()
    Snacks.picker.diagnostics_buffer()
end, "Buffer Diagnostics")
nmap("<leader>sc", function()
    Snacks.picker.command_history()
end, "Command History")
nmap("<leader>sC", function()
    Snacks.picker.commands()
end, "Commands")
nmap("<leader>sb", function()
    Snacks.picker.buffers()
end, "Buffers")
nmap("<leader>sl", function()
    Snacks.picker.lines()
end, "Buffer Lines")
nmap("gd", function()
    Snacks.picker.lsp_definitions()
end, "Goto Definition")
nmap("gD", function()
    Snacks.picker.lsp_declarations()
end, "Goto Declaration")
nmap("gr", function()
    Snacks.picker.lsp_references()
end, "References")
nmap("gI", function()
    Snacks.picker.lsp_implementations()
end, "Goto Implementation")
nmap("gy", function()
    Snacks.picker.lsp_type_definitions()
end, "Goto T[y]pe Definition")
nmap("gai", function()
    Snacks.picker.lsp_incoming_calls()
end, "C[a]lls Incoming")
nmap("gao", function()
    Snacks.picker.lsp_outgoing_calls()
end, "C[a]lls Outgoing")
nmap("<leader>ss", function()
    Snacks.picker.lsp_symbols()
end, "LSP Symbols")
nmap("<leader>sS", function()
    Snacks.picker.lsp_workspace_symbols()
end, "LSP Workspace Symbols")
nmap("<leader>su", function()
    Snacks.picker.undo()
end, "Undo History")
